### ISSUE TITLE
과제 1. 사용자 회원가입 엔드포인트

### ISSUE THREAD

**Issue by ninaaano** [ninaaano/wanted-pre-onboarding-backend#1]
## ✅ 진행할 작업
- 이메일과 비밀번호로 회원가입할 수 있는 엔드포인트를 구현해 주세요.
- 이메일과 비밀번호에 대한 유효성 검사를 구현해 주세요.
    - 이메일 조건: @ 포함
    - 비밀번호 조건: 8자 이상
    - 비밀번호는 반드시 암호화하여 저장해 주세요.
    - 이메일과 비밀번호의 유효성 검사는 위의 조건만으로 진행해 주세요. 추가적인 유효성 검사 조건은 포함하지 마세요.

## 📝 TODO
- [ ] : Member 객체 생성
- [ ] : 이메일 유효성 검사 (@ 포함)
- [ ] : 비밀번호 유효성 검사 (8자 이상)
- [ ] : 비밀번호 암호화

## ⚙️ 기타
- 비밀번호 암호화하는 부분 학습
- 테이블 설계가 먼저일까? 클래스 생성이 먼저일까?
